platform :ios, '9.0'
use_frameworks!

target 'RecipePuppy' do
  pod 'Alamofire'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'AlamofireObjectMapper'
  pod 'SwiftLint'

  target 'RecipePuppyTests' do
    inherit! :search_paths
  end

  target 'RecipePuppyUITests' do
    inherit! :search_paths
  end
end
